DELETE FROM klien;
DELETE FROM klien_pendamping;
DELETE FROM klien_pengantin;
DELETE FROM klien_keluarga;
DELETE FROM klien_panitia;
DELETE FROM klien_vendor;

INSERT INTO klien (id_klien, username, status, tanggal, waktu, alamat, maps, tema, bahasa, acara, catatan, tamu, metatag, galeri) VALUES
('usr-001', 'mempelai', 1, '2026-10-10', '08:00', 'Gedung Pernikahan Jaya, Jakarta', 'https://maps.google.com', 'Classic White', 'Indonesia, Inggris', '[{"id":"1", "nama":"Akad Nikah", "waktu":"08:00", "deskripsi":"Prosesi Akad"}, {"id":"2", "nama":"Resepsi", "waktu":"11:00", "deskripsi":"Acara resepsi"}]', '[{"judul":"Teks Izin Nikah (Mempelai Wanita kepada Orang Tua)","konten":"Bismillahirrohmanirrohim...\n\nBapak dan Ibu yang saya cintai dan hormati,\n\nPada hari yang berbahagia ini, saya memohon maaf atas segala kesalahan dan kekhilafan yang pernah saya lakukan selama ini, baik yang disengaja maupun yang tidak disengaja.\n\nSaya memohon doa restu Bapak dan Ibu, mohon kiranya Bapak dan Ibu berkenan menikahkan saya dengan pria pilihan saya, (Sebutkan Nama Mempelai Pria), dengan mas kawin (Sebutkan Mas Kawin) dibayar tunai/ngutang.\n\nSemoga pernikahan kami senantiasa mendapat ridho dan barokah dari Allah SWT, serta kami dapat membangun keluarga yang sakinah, mawaddah, dan warahmah. Amin Ya Rabbal ''Alamin.","tipe":"deskripsi"},{"judul":"Teks Amanah dari Ayah (Untuk Mempelai Pria/Anak Perempuan)","konten":"Bismillah...\n\nAnakku tersayang, hari ini adalah hari yang bersejarah bagimu dan keluarga besar kita. Ayah dan Ibu ridho dan ikhlas melepasmu untuk mengarungi bahtera rumah tangga bersama suami pilihanmu.\n\nPesan Ayah, jadilah istri yang sholehah, berbaktilah kepada suamimu, serta selalu sabar dan bersyukur dalam menghadapi segala keadaan. Jaga nama baik dirimu, keluargamu, dan mertuamu.\n\nDoa Ayah dan Ibu akan senantiasa menyertaimu. Semoga rumah tanggamu kelak sakinah, mawaddah, dan warahmah, dilimpahkan rezeki yang berkah, dan dikaruniai keturunan yang sholeh dan sholehah. Amin.","tipe":"deskripsi"},{"judul":"Doa Penutup Acara Pernikahan","konten":"Ya Allah, Ya Tuhan kami, berkatilah pernikahan ini dengan limpahan rahmat dan kasih sayang-Mu.\n\nJadikanlah keluarga ini keluarga yang Engkau cintai, penuh dengan kedamaian, ketentraman, dan kebahagiaan.\nJauhkanlah keluarga ini dari segala mara bahaya, fitnah, dan cobaan yang memberatkan.\n\nKaruniakanlah kepada mereka keturunan yang mengikut jejak para Nabi dan Rasul, serta berikan keselamatan dan keberkahan di dunia dan akhirat. Amin Ya Rabbal ''Alamin.","tipe":"deskripsi"}]', '[{"id":"1", "nama":"Budi", "jenis":"VIP", "catatan":"Selamat menempuh hidup baru"}, {"id":"2", "nama":"Andi", "jenis":"VVIP", "catatan":"Duduk di meja depan"}]', 'https://pratamamc.my.id/gambar/source/metatag.png', 'https://drive.google.com/drive/folders/1w5S_E_L-bJb18k8V1f5mU5-mK6Cq8j-p?usp=sharing');



