-- seed-musik.sql
INSERT OR REPLACE INTO musik (id, judul, artis, rekomendasi, deskripsi, versi, link) VALUES 
('msc-001-vokal', 'Anugerah Terindah', 'Admesh', 'Kirab', 'Lagu romantis yang sangat cocok untuk mengiringi momen kirab pengantin, menciptakan suasana yang hangat dan penuh cinta.', 'Vokal', 'https://audio.jukehost.co.uk/3IEQQG6llxdqKeppqD7DZlC132A9zY7V.mp3'),
('msc-001-saxophone', 'Anugerah Terindah', 'Admesh', 'Kirab', 'Lagu romantis yang sangat cocok untuk mengiringi momen kirab pengantin, menciptakan suasana yang hangat dan penuh cinta.', 'Saxophone', 'https://audio.jukehost.co.uk/KXJ6bN4ePOBmsxqVmuzJ3QfmR0PelJlf.mp3'),

('msc-002-saxophone', 'Al-I''tiraf', 'Abu Nawas', 'Sungkeman, Pengajian', 'Lantunan syair Abu Nawas yang sangat menyentuh hati. Sangat cocok digunakan untuk momen sungkeman karena maknanya yang mendalam tentang pengakuan dosa dan permohonan ampun, menambah kekhusyukan dan penghayatan saat memohon doa restu kepada orang tua.', 'Saxophone', 'https://audio.jukehost.co.uk/ElNe2POASeeUTGStwMG9uNVXMlivKe26.mp3'),

('msc-004-vokal', 'Sampai Jadi Debu', 'Banda Neira', 'Penyandingan', 'Pengantin wanita keluar dari rumah atau ruang persiapan dengan didampingi oleh orang tua atau perwakilan keluarga, lalu berjalan perlahan menuju tempat akad untuk menghampiri pengantin pria sebagai simbol penyerahan dan awal pertemuan sebelum prosesi pernikahan dimulai.', 'Vokal', 'https://audio.jukehost.co.uk/hw76qpYZfKdTPH1Ha72Cyykn1SPD44Yl.mp3'),
('msc-004-piano', 'Sampai Jadi Debu', 'Banda Neira', 'Penyandingan', 'Pengantin wanita keluar dari rumah atau ruang persiapan dengan didampingi oleh orang tua atau perwakilan keluarga, lalu berjalan perlahan menuju tempat akad untuk menghampiri pengantin pria sebagai simbol penyerahan dan awal pertemuan sebelum prosesi pernikahan dimulai.', 'Piano', 'https://audio.jukehost.co.uk/PuJ2ShCaVz9BMkngtUy2X2ouBwGdg4fl.mp3'),
('msc-004-saxophone', 'Sampai Jadi Debu', 'Banda Neira', 'Penyandingan', 'Pengantin wanita keluar dari rumah atau ruang persiapan dengan didampingi oleh orang tua atau perwakilan keluarga, lalu berjalan perlahan menuju tempat akad untuk menghampiri pengantin pria sebagai simbol penyerahan dan awal pertemuan sebelum prosesi pernikahan dimulai.', 'Saxophone', 'https://audio.jukehost.co.uk/EwudXf1sKcOdxQQsaNnvfhMugGxeiPxF.mp3'),

('msc-005-vokal', 'Beautiful In White', 'Westlife', 'Kirab, Mingle', 'Lagu klasik pernikahan yang indah, sangat cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Vokal', 'https://audio.jukehost.co.uk/Qr3vSC8JFTNSy0FU5ePxiDFkvVGnLTPv.mp3'),
('msc-005-piano', 'Beautiful In White', 'Westlife', 'Kirab, Mingle', 'Lagu klasik pernikahan yang indah, sangat cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Piano', 'https://audio.jukehost.co.uk/ghfoyQUGumjlqfKcqm5yVCyRLlqmUXcE.mp3'),
('msc-005-violin', 'Beautiful In White', 'Westlife', 'Kirab, Mingle', 'Lagu klasik pernikahan yang indah, sangat cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Violin', 'https://audio.jukehost.co.uk/QCva2KpYPyUE4kZFtCWRN2JF2WcRMsHe.mp3'),
('msc-005-saxophone', 'Beautiful In White', 'Westlife', 'Kirab, Mingle', 'Lagu klasik pernikahan yang indah, sangat cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Saxophone', 'https://audio.jukehost.co.uk/8myDBfiX9sZjYGHp8IjDCSgzFiZiKmpI.mp3'),

('msc-006-violin', 'Blue', 'Yung Kai', 'Mingle', 'Lagu dengan nuansa santai dan romantis, pas untuk menemani momen mingle bersama para tamu undangan.', 'Violin', 'https://audio.jukehost.co.uk/nitzVv28xdtYpGTk1vitEItO62y9zCDa.mp3'),

('msc-007-vokal', 'Perfect', 'Ed Sheeran', 'Kirab, Mingle', 'Lagu romantis yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Vokal', 'https://audio.jukehost.co.uk/lyEliGrbIWt4iVMzPaTNQkapTK9mMBGh.mp3'),
('msc-007-piano', 'Perfect', 'Ed Sheeran', 'Kirab, Mingle', 'Lagu romantis yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Piano', 'https://audio.jukehost.co.uk/AMkVrGitZ7PpZHQtDw2gooj1LPwFgZPo.mp3'),
('msc-007-violin', 'Perfect', 'Ed Sheeran', 'Kirab, Mingle', 'Lagu romantis yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Violin', 'https://audio.jukehost.co.uk/mCiiCl5916Io0iufYrof4HrgKlPfjQdj.mp3'),
('msc-007-saxophone', 'Perfect', 'Ed Sheeran', 'Kirab, Mingle', 'Lagu romantis yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Saxophone', 'https://audio.jukehost.co.uk/esGdCwYh7iXwZrHbCEjmL5PY4VVe08sD.mp3'),

('msc-008-saxophone', 'Nothing''s Gonna Change My Love For You', 'George Benson', 'Mingle, Kirab', 'Lagu romantis klasik yang sangat cocok untuk mengiringi momen mingle (berbaur dengan tamu) dan kirab pengantin, menciptakan suasana yang hangat dan penuh cinta.', 'Saxophone', 'https://audio.jukehost.co.uk/sZAcQQaXr0ret20OFJsjBwfP1CeMWqfv.mp3'),

('msc-009-violin', 'Until I Found You', 'Stephen Sanchez', 'Penyandingan, Mingle, Kirab', 'Lagu dengan nuansa romantis yang manis, pas untuk mengiringi momen penyandingan, mingle bersama tamu undangan, maupun saat prosesi kirab pengantin.', 'Violin', 'https://audio.jukehost.co.uk/2kvDiqVaoldNtPG1qrUE2P3yoGV9EIPH.mp3'),

('msc-010-vokal', 'Kawih Saweran 1', 'Sunda', 'Sunda, Saweran', 'Lantunan tradisional Sunda yang khusus digunakan untuk mengiringi prosesi adat saweran, memberikan nuansa sakral dan penuh makna.', 'Vokal', 'https://audio.jukehost.co.uk/yNT9SLEO47fI6PbNgB4OzRwAyRwyofUx.mp3'),

('msc-011-vokal', 'Kawih Saweran 2', 'Sunda', 'Sunda, Saweran', 'Lantunan tradisional Sunda yang khusus digunakan untuk mengiringi prosesi adat saweran, memberikan nuansa sakral dan penuh makna.', 'Vokal', 'https://audio.jukehost.co.uk/htm8DqAtknZFmtsCzPKCv7TyVLi899lo.mp3'),

('msc-012-vokal', 'Sabilulungan Instrumen', 'Sunda', 'Sunda, Prosesi Adat', 'Instrumen tradisional Sunda yang mengalun syahdu, sangat tepat untuk mengiringi berbagai rangkaian prosesi adat pernikahan Sunda.', 'Vokal', 'https://audio.jukehost.co.uk/BF7iKNiQm12sKCoLNVrojz7QKAhs445J.mp3'),

('msc-013-vokal', 'Sancang Sulin', 'Sunda', 'Sunda, Prosesi Adat', 'Instrumen tradisional Sunda yang mengalun syahdu, sangat tepat untuk mengiringi berbagai rangkaian prosesi adat pernikahan Sunda.', 'Vokal', 'https://audio.jukehost.co.uk/7LJzqdI6i6mCTind9RRe2o6PwMhJQ81G.mp3'),

('msc-014-vokal', 'Ayun Ambing Instrument', 'Sunda', 'Sunda, Prosesi Adat', 'Instrumen tradisional Sunda yang mengalun syahdu, sangat tepat untuk mengiringi berbagai rangkaian prosesi adat pernikahan Sunda.', 'Vokal', 'https://audio.jukehost.co.uk/a4zb1q9k4C3Dd0rU8iM4tZTzVSzwqlgv'),

('msc-015-vokal', 'Can''t Help Falling In Love', 'Elvis Presley', 'Mingle, Kirab', 'Lagu romantis klasik yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Vokal', 'https://audio.jukehost.co.uk/t923ggQAhXz4XS6AKKB8cUtMstVTrrpH.mp3'),
('msc-015-piano', 'Can''t Help Falling In Love', 'Elvis Presley', 'Mingle, Kirab', 'Lagu romantis klasik yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Piano', 'https://audio.jukehost.co.uk/tmp38Z3AFl2867wkdkHeike5w2r94PhA.mp3'),
('msc-015-violin', 'Can''t Help Falling In Love', 'Elvis Presley', 'Mingle, Kirab', 'Lagu romantis klasik yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Violin', 'https://audio.jukehost.co.uk/SZ0bm2timryLvqMqDezdp38KNRECk61Q.mp3'),
('msc-015-saxophone', 'Can''t Help Falling In Love', 'Elvis Presley', 'Mingle, Kirab', 'Lagu romantis klasik yang sangat populer, cocok untuk mengiringi momen kirab pengantin dan saat berbaur dengan para tamu undangan (mingle).', 'Saxophone', 'https://audio.jukehost.co.uk/5AZgSg47IcubW0GScu8NEQMumznZzl9D.mp3'),

('msc-016-vokal', 'Janji Suci', 'Yovie & Nuno', 'Mingle, Kirab, Penyandingan', 'Lagu populer yang menceritakan tentang janji setia, cocok untuk momen penyandingan, kirab pengantin, dan saat berbaur dengan para tamu (mingle).', 'Vokal', 'https://audio.jukehost.co.uk/4SOivu20BRd4Yr0G22YfjFmtImeAOFWL.mp3'),
('msc-016-piano', 'Janji Suci', 'Yovie & Nuno', 'Mingle, Kirab, Penyandingan', 'Lagu populer yang menceritakan tentang janji setia, cocok untuk momen penyandingan, kirab pengantin, dan saat berbaur dengan para tamu (mingle).', 'Piano', 'https://audio.jukehost.co.uk/ytvhKlnreNTI68j3QYYrb3kgZErC6jlc.mp3'),
('msc-016-violin', 'Janji Suci', 'Yovie & Nuno', 'Mingle, Kirab, Penyandingan', 'Lagu populer yang menceritakan tentang janji setia, cocok untuk momen penyandingan, kirab pengantin, dan saat berbaur dengan para tamu (mingle).', 'Violin', 'https://audio.jukehost.co.uk/owX3iVheYEFMmPYTB6sgVzf96n7jWLRO.mp3'),
('msc-016-saxophone', 'Janji Suci', 'Yovie & Nuno', 'Mingle, Kirab, Penyandingan', 'Lagu populer yang menceritakan tentang janji setia, cocok untuk momen penyandingan, kirab pengantin, dan saat berbaur dengan para tamu (mingle).', 'Saxophone', 'https://audio.jukehost.co.uk/UoZIhEFZ32z1WkqbBaURhS3FqwR4GVZF.mp3'),

('msc-017-vokal', 'DJ Maumere X Fa Mi Re', 'Unknown', 'Mingle, Flashmob', 'Lagu dengan irama yang ceria dan asyik untuk berjoget, sangat cocok untuk momen flashmob atau saat mingle yang santai dan menyenangkan.', 'Vokal', 'https://audio.jukehost.co.uk/DoivQJtYByS1lqm6jPPO77RuA0hbCkZF.mp3'),

('msc-018-vokal', 'DJ Tia Monika x Clbk x Wutwut x Lampu kaka', 'Unknown', 'Mingle, Flashmob', 'Lagu dengan irama yang ceria dan asyik untuk berjoget, sangat cocok untuk momen flashmob atau saat mingle yang santai dan menyenangkan.', 'Vokal', 'https://audio.jukehost.co.uk/QnKva0myKm4vsI0ebmrR0M5QRWmHVGIO.mp3'),

('msc-019-vokal', 'DJ Tor monitor ketua x Tabola bale x Ngapain repot', 'Unknown', 'Mingle, Flashmob', 'Lagu dengan irama yang ceria dan asyik untuk berjoget, sangat cocok untuk momen flashmob atau saat mingle yang santai dan menyenangkan.', 'Vokal', 'https://audio.jukehost.co.uk/eaF1ggxfYjkDPF6yOWZCbs0b9EbNGHa1.mp3'),

('msc-020-vokal', 'Cinta Sejati', 'Bunga Citra Lestari', 'Kirab, Mingle, Penyandingan', 'Lagu romantis yang mendalam tentang cinta sejati, sangat cocok untuk mengiringi berbagai momen sakral dan romantis dalam pernikahan.', 'Vokal', 'https://audio.jukehost.co.uk/HEcXu0NXROmBGnRMPeO5nrkPCqgd1Gh5.mp3'),
('msc-020-violin', 'Cinta Sejati', 'Bunga Citra Lestari', 'Kirab, Mingle, Penyandingan', 'Lagu romantis yang mendalam tentang cinta sejati, sangat cocok untuk mengiringi berbagai momen sakral dan romantis dalam pernikahan.', 'Violin', 'https://audio.jukehost.co.uk/KqWRCUH3x6kJs9kfeCividijOJyvrLAp.mp3'),
('msc-020-saxophone', 'Cinta Sejati', 'Bunga Citra Lestari', 'Kirab, Mingle, Penyandingan', 'Lagu romantis yang mendalam tentang cinta sejati, sangat cocok untuk mengiringi berbagai momen sakral dan romantis dalam pernikahan.', 'Saxophone', 'https://audio.jukehost.co.uk/ZkAFyaXCqjwLPHQTRNxFKTO6h8J5Fgoh.mp3'),

('msc-021-vokal', 'Ketika Cinta Bertasbih', 'Melly Goeslaw', 'Kirab, Mingle, Penyandingan', 'Lagu bernuansa religius yang indah, cocok untuk pernikahan dengan konsep islami, mengiringi momen kirab atau penyandingan.', 'Vokal', 'https://audio.jukehost.co.uk/ayWl5HL5qjD1KSS9yBnqnT11rF9wgluX.mp3'),
('msc-021-violin', 'Ketika Cinta Bertasbih', 'Melly Goeslaw', 'Kirab, Mingle, Penyandingan', 'Lagu bernuansa religius yang indah, cocok untuk pernikahan dengan konsep islami, mengiringi momen kirab atau penyandingan.', 'Violin', 'https://audio.jukehost.co.uk/qgJfXN4oMfok6dmHEebHdB6qr4sdAj47.mp3'),
('msc-021-saxophone', 'Ketika Cinta Bertasbih', 'Melly Goeslaw', 'Kirab, Mingle, Penyandingan', 'Lagu bernuansa religius yang indah, cocok untuk pernikahan dengan konsep islami, mengiringi momen kirab atau penyandingan.', 'Saxophone', 'https://audio.jukehost.co.uk/nRkQaREsTsQe10R6nSNrRTclAopUxxu2.mp3'),

('msc-022-vokal', 'Ayat Ayat Cinta', 'Rossa', 'Kirab, Mingle, Penyandingan', 'Lagu romantis bernuansa islami yang sangat populer, pas untuk mengiringi momen-momen penuh haru dan bahagia di hari pernikahan.', 'Vokal', 'https://audio.jukehost.co.uk/IabolzcDilHvAkW9GukZK0cHjSe3fQ1U.mp3'),
('msc-022-orkestra', 'Ayat Ayat Cinta', 'Rossa', 'Kirab, Mingle, Penyandingan', 'Lagu romantis bernuansa islami yang sangat populer, pas untuk mengiringi momen-momen penuh haru dan bahagia di hari pernikahan.', 'Orkestra', 'https://audio.jukehost.co.uk/zxzB5xxs4SMv2zaceTT8T6xqDkboHTIJ.mp3'),
('msc-022-violin', 'Ayat Ayat Cinta', 'Rossa', 'Kirab, Mingle, Penyandingan', 'Lagu romantis bernuansa islami yang sangat populer, pas untuk mengiringi momen-momen penuh haru dan bahagia di hari pernikahan.', 'Violin', 'https://audio.jukehost.co.uk/whJidWnCfu6xJX5qq3yAifMwfDQ1Bdu4.mp3'),
('msc-023', 'Flashmob Remix', 'Remix', 'Mingle, Flashmob', 'Gabungan lagu gerong, mojang priangan, domba kuring & kicau mania', 'Vokal', 'https://audio.jukehost.co.uk/019eb4d7-abbf-70af-96b4-cc9ae06b860e');
