-- seed-edukasi.sql
INSERT OR REPLACE INTO edukasi (id, kategori, judul, deskripsi, gambar, makna, pelaksanaan, video) VALUES 
('edu-akd-01', 'formal', 'Sambutan Penyerahan & Penerimaan Pengantin', 'Prosesi dialogis pembuka yang mengawali seluruh rangkaian pernikahan. Pihak keluarga calon pengantin pria secara resmi mengutarakan niat baik kedatangan mereka, yaitu untuk menyerahkan putra tercintanya beserta seluruh tanggung jawab lahir batin kepada keluarga wanita. Hal ini kemudian disambut hangat oleh perwakilan keluarga wanita yang menyatakan penerimaan secara tulus, mengesampingkan segala keraguan, dan menyatukan komitmen untuk saling mengikat tali persaudaraan antar dua keluarga besar yang berbeda latar belakang.', '/gambar/edukasi/akad-sambutan.webp', 'Bukan sekadar formalitas, prosesi ini adalah simbolisasi penyerahan tongkat estafet pembinaan kehidupan. Pihak pria memercayakan putranya untuk dibimbing, sedangkan pihak wanita memberikan pintu terbuka yang melambangkan kebesaran hati keluarga dalam menyambut menantu sebagai anak kandung sendiri. Ini memperkokoh pondasi psikologis kedua keluarga sebelum ijab kabul diikrarkan.', '1. Rombongan keluarga pria tiba dan dipersilakan menempati posisi berhadapan dengan keluarga wanita.
2. Juru bicara atau utusan khusus keluarga pria berdiri, memaparkan secara formal maksud dan tujuan agung kedatangan rombongan, memohon izin, serta menyerahkan calon pengantin pria seutuhnya.
3. Juru bicara keluarga wanita membalas dengan pidato penerimaan yang berisi rasa syukur, kesiapan menerima sang pria, serta doa kebaikan untuk acara selanjutnya.
4. Acara ditutup dengan jabat tangan simbolis antara kedua belah pihak sebagai bentuk kesepakatan batin, disusul mengarahkan pengantin ke meja akad.', NULL),

('edu-akd-02', 'formal', 'Pembacaan Ayat Suci Al-Quran', 'Lantunan kalam Ilahi yang dipilih secara khusus (biasanya merujuk pada ayat-ayat pernikahan seperti Ar-Rum ayat 21) sebagai landasan spiritual sebelum memasuki inti acara. Pembacaan ini dilakukan oleh qori atau qoriah dengan tartil, membawa suasana sakral dan hening ke dalam ruangan.', '/gambar/edukasi/akad-baca-quran.webp', 'Sebagai manifestasi ketundukan kepada Sang Pencipta, memohon curahan rahmat, keberkahan, keberlimpahan rezeki, serta ketenangan batin. Ayat yang dilantunkan bertindak sebagai pengingat fundamental bahwa pernikahan adalah ibadah terpanjang yang sangat diagungkan dalam agama.', '1. Pembawa acara mempersilakan qori/qoriah untuk melantunkan ayat suci Al-Quran dan sari tilawah.
2. Calon pengantin, orang tua, wali, dan seluruh hadirin menundukkan pandangan, mendengarkan secara khusyuk dan hening.
3. Ditutup dengan pemaknaan dari sari tilawah yang merefleksikan keagungan ibadah pernikahan.', NULL),

('edu-akd-03', 'formal', 'Amanah Nikah dari Ayah/Wali', 'Momen puncak emosional di mana seorang figur ayah atau wali nikah memberikan wejangan terakhir, mutiara nasihat, dan amanat kehidupan rumah tangga tepat sebelum melangsungkan ijab kabul. Pesan ini seringkali disampaikan dengan suara bergetar karena mengandung memori pengasuhan sejak kecil hingga melepaskan sang anak membangun keluarga baru.', '/gambar/edukasi/akad-amanah.webp', 'Sebagai bentuk pelepasan tanggung jawab moral secara formal dan penyerahan tongkat kepemimpinan. Ayah menyalurkan doa restu, membekali calon suami istri dengan pandangan hidup, ketangguhan mental, serta mengingatkan pentingnya memegang teguh komitmen saat badai rumah tangga menerpa.', '1. Ayah atau wali duduk berhadapan dengan calon pengantin (terutama pengantin pria).
2. Dengan suasana hati yang hening, ayah menatap wajah sang anak dan calon menantu, lalu menyampaikan wejangan kehidupan secara lisan.
3. Pesan diakhiri dengan ikrar penyerahan tanggung jawab perwalian, yang diaminkan oleh saksi dan hadirin yang biasanya ikut merasakan keharuan.', NULL),

('edu-akd-04', 'formal', 'Izin Nikah & Penerimaan', 'Ritual sakral permohonan restu di mana calon pengantin wanita/pria secara langsung memohon ampun atas segala khilaf selama masa pengasuhan, lalu memohon izin untuk dinikahkan dengan pilihan hatinya. Orang tua kemudian merespons dengan memberikan kerelaan penuh, memaafkan segala kesalahan putrinya, dan merestuinya melangkah ke pelaminan.', '/gambar/edukasi/akad-izin-nikah.webp', 'Sebagai wujud bakti tanpa pamrih seorang anak, bentuk kerendahan hati untuk tidak melangkahi ridho orang tua. Ridho Allah SWT bergantung pada ridho orang tua, sehingga restu ini adalah kunci pembuka pintu surga dan kelancaran kehidupan rumah tangga yang akan diarungi.', '1. Calon pengantin wanita (seringkali sudah disandingkan atau masih di ruang tunggu) dengan suara lirih sambil menangis membacakan teks permohonan izin nikah kepada ayah dan ibundanya.
2. Calon pengantin mencium tangan kedua orang tuanya sebagai tanda bakti terdalam.
3. Ayah membaca jawaban atas permohonan tersebut, menyatakan pemberian maaf lahir batin, keikhlasan merestui, serta kesiapan untuk segera menikahkan putrinya dengan calon suami.', NULL),

('edu-akd-05', 'formal', 'Khutbah Nikah', 'Pemaparan syariat dan filosofi pernikahan yang dibawakan oleh penghulu dari KUA atau pemuka agama (ulama). Khutbah ini memuat poin-poin krusial terkait hukum, hak dan kewajiban pasangan suami istri, hingga tata cara menyelesaikan konflik rumah tangga berdasarkan pedoman agama.', '/gambar/edukasi/akad-khutbah-nikah.webp', 'Sebagai bekal ilmu aplikatif dan komprehensif bagi kedua mempelai sebelum sah menjadi suami istri. Khutbah menjadi rem pengingat bahwa pernikahan ditujukan untuk menggapai keluarga yang sakinah (tenang), mawaddah (cinta), dan rahmah (kasih sayang).', '1. Sebelum lafadz ijab kabul dibacakan, penghulu meminta waktu sejenak untuk memaparkan khutbah.
2. Penghulu membacakan rukun dan syarat nikah, dilanjutkan dengan nasihat teknis seputar berumah tangga.
3. Mempelai pria yang tengah menggenggam tangan wali mendengarkan dengan penuh konsentrasi dan afirmasi.', NULL),

('edu-akd-06', 'formal', 'Akad Nikah / Pemberkatan', 'Inilah titik transisi antara hukum haram menjadi halal, janji terberat yang menggetarkan tiang arasy. Ijab (penyerahan dari wali) dan Kabul (penerimaan dari pengantin pria) diikrarkan dengan tegas, lugas, dan sekali napas di hadapan sang pencipta, saksi, dan pemuka agama. Segera setelah saksi meneriakkan kata "Sah!", status keduanya secara legal dan agama berubah menjadi suami istri.', '/gambar/edukasi/akad-ijab-kabul.webp', 'Momentum perjanjian berat (Mitsaqan Ghalidza) yang mengharuskan sang putra mengambil alih seluruh dosa, nafkah, nasib, dan perlindungan atas sang wanita dari pundak ayahnya. Merupakan pengesahan agung yang menyatukan dua insan di mata manusia dan Tuhan.', '1. Penghulu mengecek kembali segala kelengkapan administrasi dan mahar.
2. Wali nikah menggenggam erat tangan kanan pengantin pria (bisa dengan variasi meletakkan jempol saling bertemu).
3. Wali mengucapkan kalimat Ijab (berisi nama mempelai, perwalian, dan besaran mahar).
4. Tanpa jeda, pengantin pria merespons dengan mantap kalimat Kabul.
5. Saksi mengonfirmasi dengan kata "Sah", ditutup dengan doa keberkahan, pembacaan sighat taklik, dan penyerahan mahar serta buku nikah.', NULL),

('edu-adt-01', 'adat', 'Simbolis Seserahan', 'Prosesi pembuka di balik layar atau di panggung akad di mana ibu dari mempelai pria menyerahkan sekotak hantaran (bisa berupa perhiasan, pakaian, atau barang pecah belah) kepada ibu dari mempelai wanita. Hantaran ini merupakan manifestasi dari sanggulung (bekal fisik).', '/gambar/edukasi/adat-seserahan.webp', 'Sebagai penanda kemapanan finansial dan tanda cinta kasih secara material. Seserahan melambangkan kemampuan dan kesiapan calon suami untuk menafkahi istrinya, serta sebagai "tanda mata" pengikat tali persaudaraan antar dua keluarga besar.', '1. Ibu mempelai pria mewakili keluarga membawa satu kotak seserahan utama (seperti seperangkat perhiasan atau alat sholat).
2. Diserahkan dengan penuh kelembutan kepada ibu mempelai wanita sambil tersenyum.
3. Keduanya berfoto mengabadikan momen simbolis ini sebelum hantaran-hantaran lainnya diletakkan ke meja sangjit/seserahan secara estafet.', NULL),

('edu-adt-02', 'adat', 'Siraman', 'Ritual penyucian diri yang sangat mendalam dan penuh filosofi. Calon pengantin mengenakan ronce melati dan kain batik khusus, kemudian dimandikan menggunakan air yang telah dicampur dengan tujuh macam bunga wangi (Kembang Setaman). Biasanya dilakukan sehari sebelum acara akad nikah berlangsung.', '/gambar/edukasi/adat-siraman.webp', 'Siraman berasal dari kata "Siram" yang berarti mandi. Maknanya bukan sekedar membersihkan tubuh fisik, melainkan membersihkan jiwa, mengikis sifat egois, dan menggugurkan sisa-sisa dosa masa lampau. Tujuannya adalah agar pada hari H raga berbau harum dan jiwa putih bersih dari segala aura magis yang negatif.', '1. Calon pengantin memohon doa restu (sungkem) kepada orang tuanya.
2. Pengantin diarahkan duduk di kursi yang telah dihias sedemikian rupa.
3. Sebanyak tujuh atau sembilan orang sesepuh (yang telah memiliki kehidupan rumah tangga harmonis) secara bergantian menyiramkan air suci ke ubun-ubun, pundak, hingga kaki calon pengantin.
4. Diakhiri dengan penyiraman air wudhu oleh ayahanda sebagai bentuk penutupan penyucian.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-adt-03', 'adat', 'Pengalungan Bunga', 'Sebagai gerbang pertama pada hari H upacara pernikahan, kedatangan rombongan mempelai pria dicegat dengan rasa hormat. Ibu dan ayah mempelai wanita menghampiri, lalu ibu mertua mengalungkan sebuah lingkaran bunga melati (ronce) yang segar dan harum di leher calon menantunya.', '/gambar/edukasi/adat-pengalungan-bunga.webp', 'Ronce melati melambangkan keharuman, ketulusan, dan kemurnian. Pengalungan ini adalah bahasa non-verbal dari ibu mertua yang mengisyaratkan bahwa beliau telah sepenuhnya melepaskan sang pria dari identitas lamanya, menariknya masuk ke dalam pelukan identitas keluarga yang baru sepenuh hati.', '1. Mempelai pria dan keluarga berdiri di depan lokasi acara (pintu masuk).
2. Perwakilan tuan rumah datang menjemput, orang tua mempelai wanita maju ke depan.
3. Ibu mempelai wanita mengambil ronce melati di nampan, membentangkannya, lalu mengalungkannya ke leher sang menantu dengan senyuman.
4. Ayah mempelai wanita lalu menggandeng atau merangkul menantunya menuju meja Ijab Kabul.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-adt-04', 'adat', 'Mapag Panganten', 'Prosesi kolosal penyambutan raja dan ratu sehari dalam budaya Sunda. Diarak dengan kemegahan seni teatrikal yang dipimpin oleh tokoh rekaan bernuansa jenaka namun mistis, "Ki Lengser" dan "Ambu". Prosesi ini sangat kaya warna, meriah oleh iringan alat musik tradisional (Gamelan Degung), serta aksi lemah gemulai penari payung.', '/gambar/edukasi/adat-mapag-panganten.webp', 'Prosesi ini merajut harmoni antara nilai penghormatan tinggi kepada pengantin dengan pelestarian budaya lokal. Ki Lengser adalah representasi dari sesepuh atau utusan raja yang turun gunung untuk memberikan restu, mendampingi, serta mengiringi jalan hidup baru kedua mempelai penuh dengan gelak tawa dan wejangan tersembunyi.', '1. Kedua mempelai bersiap di pintu masuk venue sesaat sebelum resepsi dimulai.
2. Gamelan degung bertalu-talu membunyikan nada renggong manis.
3. Lengser maju menari komedi, berinteraksi dengan penonton, lalu menjemput mempelai.
4. Penari merak dan pemegang payung emas memayungi mempelai, menuntun langkah demi langkah dalam irama tarian Sunda yang meditatif menuju takhta pelaminan.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-adt-05', 'adat', 'Sungkeman', 'Sebuah prosesi krusial yang bisa memecah tangis satu ruangan. Kedua pengantin yang baru sah menikah akan secara bergantian merendahkan tubuhnya, bersujud (bersimpuh) di pangkuan kedua orang tua dan mertuanya, sambil memegang lutut dan mencium tangan mereka.', '/gambar/edukasi/adat-sungkeman.webp', 'Merupakan titik lebur keangkuhan manusia. Merepresentasikan bakti tertinggi anak kepada sang penciptanya (melalui orang tua). Permohonan maaf yang dituturkan menjadi sarana untuk melunturkan amarah terpendam atau sisa kekecewaan, memastikan rute perjalanan rumah tangga bersih dari segala "kualat" sekaligus meraup doa mustajab.', '1. Kursi orang tua dan mertua disusun saling berhadapan di depan pelaminan.
2. Mempelai pria bersimpuh di haribaan ayah/ibunya, sedangkan wanita di orang tua pria (atau sebaliknya).
3. Sang anak menundukkan kepala sangat dalam, mengucapkan permohonan maaf dan terima kasih dengan nada berbisik.
4. Orang tua membalas dengan memeluk leher sang anak, mengusap punggung dan kepalanya sambil menitikkan air mata serta membacakan doa.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-adt-06', 'adat', 'Saweran', 'Sesi interaktif dan penuh energi di mana pengantin akan dipayungi, lalu pemandu adat akan menyanyikan "Kidung Sawer" yang penuh pepatah. Di saat bersamaan, potongan uang logam, beras kuning, kunyit beriris tipis, hingga permen, ditaburkan berkali-kali kepada tamu penonton.', '/gambar/edukasi/adat-saweran.webp', 'Beras perlambang sandang pangan dan kemakmuran tiada henti. Uang logam mencerminkan kelimpahan kekayaan finansial. Permen memberi nuansa harmonis dan manisnya kehidupan, sementara kunyit menolak bala. Semuanya ditaburkan agar pengantin senantiasa teringat untuk dermawan kepada sesama tatkala mendulang sukses nantinya.', '1. Sepasang pengantin didudukkan berhimpitan di bawah naungan satu payung kebesaran yang dipegang oleh kerabat.
2. Penyanyi adat melantunkan tembang pantun/kidung berisi filsafat membangun rumah tangga yang kukuh.
3. Orang tua mengambil taburan dari bokor kuningan, lalu melempar-lemparkannya dari atas kepala pengantin ke kerumunan tamu.
4. Terjadi keriuhan gembira ketika tamu anak-anak maupun dewasa berebut mendapat permen dan koin.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-adt-07', 'adat', 'Huap Lingkung', 'Rangkaian prosesi makanan yang berisi filosofi mendalam. Orang tua akan menyuapi kedua pengantin untuk terakhir kalinya, lalu pengantin saling menyuapkan sepiring nasi berisi lauk ayam utuh (bakakak) dan saling memperebutkan ayam tersebut. Yang mendapatkan puing lebih besar, itu yang diyakini membawa rejeki lebih besar, namun pada akhirnya tetap akan dibelah dua untuk pasangannya.', '/gambar/edukasi/adat-huap-lingkung.webp', 'Huap Lingkung (suapan terakhir) bermakna pemutusan tali tanggung jawab orang tua secara resmi dalam memberi makan sang anak. Sedang acara tarik bakakak ayam adalah simulasi manajemen rumah tangga: bahwa sebesar apa pun penghasilan ego yang didapat oleh suami atau istri, semuanya harus disinergikan, saling berbagi, dan dinikmati bersama secara adil dan merata.', '1. Ibunda dan ayahanda memegang sekepal kecil nasi tumpeng kuning, menyuapkannya ke mulut anak dan menantunya bergantian.
2. Pengantin saling menyendokkan nasi kuning ke mulut satu sama lain.
3. Panitia meletakkan ayam panggang utuh (bakakak) di atas meja. MC menghitung aba-aba mundur "3, 2, 1!", lalu masing-masing pengantin menarik paha/sayap ayam secara berlawanan arah hingga ayam tersebut terkoyak.
4. Potongan ayam yang besar kemudian digigit bersama-sama.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-adt-08', 'adat', 'Meleum Harupat', 'Dalam ritual ini, mempelai pria menyalakan tujuh batang lidi daun aren (harupat) ke atas lilin hingga apinya berkobar. Kemudian, lidi yang sedang terbakar dicelupkan ke dalam mangkuk perunggu (bokor) berisi air yang dipegang erat oleh istrinya hingga api tersebut berdesis padam dengan asap mengepul. Setelah padam, lidi tersebut dipatahkan dan dibuang ke tanah.', '/gambar/edukasi/adat-meleum-harupat.webp', 'Tujuh lidi menyimbolkan tujuh hari dalam seminggu, sementara api yang menyala melambangkan tempramen, amarah, ego dan kobaran nafsu maskulin yang panas pada pria. Air yang dipegang istri merepresentasikan kelembutan, keteduhan dan kesabaran seorang ibu rumah tangga. Pematahan lidi bermakna bahwa seluruh bara amarah sang suami harus mampu diredam oleh kesejukan dari sang istri agar kehidupan hancur lebur dapat dihindarkan.', '1. MC memberikan penjelasan maknawi sambil memberikan tujuh lidi (harupat) ke tangan mempelai pria.
2. Mempelai pria membakar ujung lidi pada lentera hingga menyala dengan cukup besar.
3. Mempelai wanita mendekatkan kendi berisikan kembang dan air di bawah api tersebut.
4. Mempelai pria merendam api ke dalam air secara perlahan hingga padam berdesis.
5. Mempelai pria mematahkan seluruh lidi tersebut dengan kedua tangannya dengan kekuatan penuh lalu membuangnya ke wadah buangan.', NULL),

('edu-adt-09', 'adat', 'Mepeus Kendi', 'Segera sesudah ashab dan masalah rumah tangga diredakan melalui simbol harupat, kendi yang menyimpan air tersebut memiliki sisa tugas akhir. Kendi tanah liat itu kemudian dilemparkan secara kuat hingga pecah berantakan berkeping-keping di atas lantai oleh ibunda mempelai wanita (atau oleh kedua mempelai secara bersama-sama).', '/gambar/edukasi/adat-mepeus-kendi.webp', 'Kendi merepresentasikan wadah masa lalu (masa lajang). Memecahkan kendi artinya mendobrak garis batas kelajangan. Pecahnya kendi diakhiri dengan tumpahnya air, yang menyimbolkan air kehidupan akan mengalir deras sehingga memancarkan rezeki keberkahan pada benih-benih harapan yang akan tumbuh di kehidupan mereka. Ini juga sebagai doa agar pasangan tersebut kelak memecahkan kebuntuan hidup.', '1. Ibunda pengantin wanita mengambil kendi air sisa meleum harupat (atau disediakan kendi terpisah khusus).
2. Dengan kesepakatan pandangan dan aba-aba pemandu, ibu/pengantin melepaskan pegangannya atau melempar sedikt keras kendi ke ubin beralaskan alas karpet/papan hingga terdengar bunyi pecah berdenting.
3. Sorak hadirin mengiringi pecahnya kendi yang menandai berakhirnya ego masing-masing.', NULL),

('edu-adt-10', 'adat', 'Nincak Endog', 'Mempelai pria tanpa beralas kaki diminta berdiri di atas sebuah papan kecil yang disediakan satu butir telur mentah utuh. Ia kemudian mendesakkan telapak kakinya hingga telur tersebut remuk. Setelah kakinya bersimbah kuning telur, sang istri yang sudah duduk bersimpuh dan menyiapkan air bunga bergegas membasuh, mencuci, dan mengeringkan kaki suaminya tersebut dengan handuk bersih hingga tak tersisa kotoran sedikit pun.', '/gambar/edukasi/adat-nincak-endog.webp', 'Prosesi ini mengandung pesan kepatuhan dan manajemen rumah tangga yang kuat. Pecahnya telur adalah wujud kemampuan dan tanggung jawab penuh pria sebagai kepala keluarga untuk "memecahkan" keperawanan istri dan memberikan keturunan yang diharap-harapkan. Sedangkan membasuh kaki merepresentasikan rasa taat, bakti, kesetiaan, dan dedikasi penuh sang istri demi meringankan kepenatan sang nahkoda (suami) yang berjuang keras menafkahi keluarga tercinta.', '1. Panitia menyeiapkan nampan beralas khusus, meletakkan telur mentah.
2. Mempelai pria mengarahkan telapak kakinya yang polos menginjak telur perlahan hingga terdengar retak dan isi telur berhamburan ke tapak kaki.
3. Mempelai wanita membungkuk mengambil gayung perak, menyiram kaki suaminya dengan air kembang perlahan.
4. Mempelai wanita mengusap-usap membersihkan tapak kaki laki-laki itu, dilanjutkan melapnya dengan selembar handuk kecil.', NULL),

('edu-rsp-01', 'resepsi', 'Pengantaran & Temu Pengantin', 'Prosesi psikologis yang mendebarkan di mana sang pengantin wanita—yang selama ijab kabul disembunyikan di ruang rias agar tidak bersentuhan pandangan—akhirnya dituntun keluar setelah mahar diserahkan dan kata sah dideklarasikan. Sang suami akan berjalan menuju selasar ruangan, menanti di titik temu, kemudian keduanya perlahan mendekat dan bertatapan untuk pertama kalinya dengan status yang sudah sah.', '/gambar/edukasi/akad-temu-pengantin.webp', 'Momen ini menghancurkan tembok batas kesendirian. Inilah kilas pandang yang secara nyata mengubah seluruh hidup dua anak manusia. Temu ini menebalkan romansa pertemuan dua pihak, dari sekadar ikatan legal-spiritual (saat ucapan ijab) menuju ikatan visual-emosional di depan umum (ketika saling menetapkan pandangan mata dari kejauhan hingga menjadi dekat).', '1. MC memberikan jeda sesudah penandatanganan buku nikah.
2. Diiringi alunan musik pelan (seperti instrumental piano, kecapi, atau seruling), pengantin wanita dituntun perlahan oleh saudari atau pendampingnya.
3. Pengantin pria berdiri tegap di tengah lorong red carpet memandang keajaiban di depannya.
4. Ketika keduanya bertemu, suami memberikan ciuman kening, lalu menggandeng istrinya erat menuju kursi singgasana pelaminan.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-rsp-02', 'resepsi', 'Kirab Pengantin', 'Parade seremonial paling elegan dan bertabur kemewahan dari seluruh tahapan acara. Setelah jeda rias, pengantin berganti pakaian resepsi. Mereka berjalan memasuki ballroom agung bagaikan pasangan pangeran dan putri mahkota. Mereka dikawal barisan panjang para pendamping (bridesmaid, groomsmen, tim pedang pora militer jika dari kalangan aparat, atau cucuk lampah tarian tradisional) membelah ribuan mata yang menatap kagum.', '/gambar/edukasi/resepsi-kirab.webp', 'Kirab merupakan bentuk pengumuman publik (Walimah) yang sah secara defacto bahwa sepasang anak muda ini telah sah memisahkan diri dari ketergantungan orang tua dan memulai sebuah "kerajaan" atau rumah tangganya sendiri. Taburan senyum dan megahnya lagu di sepanjang karpet merah merepresentasikan langkah awal menuju masa depan yang agung, berwibawa, penuh kepercayaan diri, dan kebanggaan dari seluruh saksi yang hadir.', '1. Sebelum kirab dimulai, master of ceremony (MC) memusatkan atensi seluruh audiens, meredupkan lampu ruangan, lalu menghidupkan sirine/musik perkenalan megah.
2. Pintu ballroom menjeblak terbuka. Barisan perintis jalan berjalan paling depan.
3. Kedua mempelai melangkah amat pelan dengan koreografi, senyuman menawan ke sisi kanan dan kiri menyapa sekilas para tamu VIP yang berdiri bertepuk tangan.
4. Orang tua beserta rombongan keluarga besar mengekor tepat satu hingga tiga meter di belakang punggung pengantin menyusuri lorong menuju lantai pelaminan megah.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-rsp-03', 'resepsi', 'Wedding Cutting Cake', 'Momen resepsi modern yang menampilkan sebuah kue pengantin berlapis tinggi (tier cake) dengan dekorasi rumit dan cantik. Dengan menggunakan pedang atau pisau berhiaskan pita mawar, kedua pengantin bergandengan tangan menancapkan pisau dan memotong satu bagian kue kecil hingga ke tumpuan paling dasar. Kadang acara ini ditutup bersulang gelas minuman (wedding toast) dengan menautkan lengan (cross-arm).', '/gambar/edukasi/resepsi-wedding-cake.webp', 'Tingkatan kue pengantin menggambarkan anak tangga perjalanan kehidupan yang semakin ke atas semakin kecil, artinya puncak kebahagiaan hanya bisa diraih melalui tantangan mendaki yang solid. Kerja sama tangan memotong kue dari hulu ke hilir adalah manifesto kekompakan saling menyokong rintangan. Saling menyuapi irisan kue tersebut menceritakan ikrar untuk selalu menyajikan pemikiran/perbuatan "manis" yang menyenangkan kepada satu sama lain seumur hidup.', '1. Lantunan lagu romantis pengiring dinaikkan volumenya. MC mengundang seluruh tamu fokus menatap letak sentral kue pernikahan pada pinggir panggung.
2. Pengantin berjalan ke stan kue, pengantin saling bertatapan dan menyeringai.
3. Pasangan menumpukkan tangan kanannya saling tumpuk memegang gagang pegangan pisau hias. Mereka menghitung mundur bersama dan mengiris kue ke arah bawah dengan perlahan.
4. Keduanya mengambil piring tatakan kecil dan menyuapi secuil kue ke pasangan secara bergantian dan meriah.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-rsp-04', 'resepsi', 'Mingle / Sapa Tamu', 'Sesi interaksi cair dan intim di paruh akhir waktu resepsi. Pengantin yang umumnya terkungkung statis berdiri di pelaminan menyalami ribuan orang dalam banjar teratur, lantas melepaskan kekakuannya dan inisiatif beranjak turun membaur, berkeliling dari meja jamuan makan ke meja lainnya dengan membawa prop (seperti gelas minuman, keranjang sovenir).', '/gambar/edukasi/resepsi-tamu-sapa.webp', 'Mingle meleburkan dimensi jarak batas strata sosial dan kesakralan formal antara raja sehari dengan rakyatnya (undangan). Turunnya pengantin membuktikan rendah hatinya kualitas manusia mereka. Percakapan ini membangun jembatan personal, momen nostalgia berfoto lebih santai dengan pose aneh/lucu bersama sahabat, hingga menghantarkan rasa syukur tak terhingga secara face-to-face ke setiap grup tamu prioritas.', '1. Di sela-sela kepadatan salaman berkurang atau jamuan makan besar telah dirasa dinikmati, MC merilis restu agar pengantin turun panggung.
2. Pengantin ditemani 1-2 staf WO menuju stand food stall tamu kolega bisnis ayah/ibu untuk bersapa obrolan pendek sambil berfoto tanpa antrean kaku.
3. Mereka bergeser menghampiri area sirkel sahabat kuliah, berpelukan renyah, melakukan video reel selfie instan, bersenda gurau bebas, lalu lanjut menyapu lantai ballroom tamu lain.', 'https://www.youtube.com/watch?v=M7FIvfx5J10'),

('edu-rsp-05', 'resepsi', 'Kecupan Pernikahan (Wedding Kiss)', 'Momen epik dan sinematik yang menjadi lambang pamungkas puncak afeksi antara sepasang kekasih modern. Diposisikan di penghujung acara sebelum bubar atau saat first dance, suami mencondongkan tubuh perlahan meraih tengkuk, lalu mendaratkan kecupan intim nan dalam kepada kening atau bibir pengantin wanita secara lembut selama beberapa detik dengan latar estetis yang magis.', '/gambar/edukasi/resepsi-wedding-kiss.webp', 'Kecupan ini menyerukan pesan kepemilikan emosional mutlak yang membanggakan (to seal the deal). Ini memecahkan tensi puluhan tahun asuhan mandiri tanpa disentuh yang kini mencair dalam validasi hakiki sebuah ikatan yang utuh tak ada jarak. Ini mendemonstrasikan letupan keindahan cinta, rasa aman batiniah sang wanita atas sandaran pria kokoh, yang disambut tepuk tangan riuh merayakan "kemenangan".', '1. Pada timing yang disiapkan, MC menahan atensi ruangan, "Ladies and gentleman, let''s secure the love!". Set efek mesin dry-ice mengeluarkan kabut awan rendah di lantai, lampu spot down light menyorot mereka berdua dalam remang-remang romantis.
2. Mempelai pria merangkul pinggang wanita agar mendekat, kemudian mengecup bibir/kening dengan keanggunan durasi lama.
3. Tiba-tiba shower bunga/confetti blast meledak perlahan dari sisi panggung seiring bidik kamera (shutter count) juru foto menangkap potret masterpiece pernikahan terbaik seumur hidup mereka.', NULL),

('edu-rsp-06', 'resepsi', 'Tarian Pernikahan (Wedding Dance)', 'Ritme sinkronisasi raga dan jiwa perdana dari dua insan dengan latar belakang sorot lampu lembut. Diiringi genre lagu yang amat berbekas dalam kenangan histori cinta mereka—entah itu balad melankolis, waltz berayun lambat, hingga rumba bergairah—pasangan ini berdansa memutar, berdekapan, berangkul sambil bertukar dialog tatap mata rahasia satu sama lain, mengisolasi semua kerumitan dunia di luar lingkaran tarian.', '/gambar/edukasi/resepsi-wedding-dance.webp', 'Kunci dari rumah tangga adalah tarian menyeimbangkan pijakan dari gesekan miskomunikasi. Ketika tubuh suami mampu merengkuh harmoni menuntun langkah dan istri merespon putaran dengan rasa aman, ini mendikte kemampuan kohesi kerja sama rumah tangga menghadapi fluktuasi kehidupan. Ini menunjukkan sinkronisitas sempurna dari chemistry cinta kasih mereka kepada peradaban manusia yang menyaksikan (dunia luar).', '1. MC mendudukkan seluruh hadirin di sekeliling lantai dansa bercahaya (led dance floor).
2. "The First Dance as Husband and Wife" diutarakan lewat mikrofon, alunan nada lambat naik daun perlahan.
3. Pengantin berjalan ke center-stage, tangan pria mantap memanggul lingkar pinggang wanitanya, lalu berdansa lembut, melayang dan mengangkat wanitanya berputar melintasi asap. 
4. Sorak kagum penonton menjadi latarnya tanpa memutus konsentrasi sakral keduanya.', NULL),

('edu-rsp-07', 'resepsi', 'Flashmob', 'Pertunjukan meledak ruah energi tak terduga sebagai suntikan adrenalin pelepas tawa meriah bagi penutup hari yang melelahkan. Biasanya bermula tenang bak ada sabotase audio dari sang DJ yang mengganti lagu menjadi hentakan beat ceria (seperti musik K-Pop, RnB, dsb). Kemudian barisan grup pertemanan atau bridesmaid hingga pengantin pria/wanita menyelinap masuk menarikan koreo yang sudah dilatih berhari-hari sebelum resepsi.', '/gambar/edukasi/resepsi-flashmob.webp', 'Bentuk pelepasan depresi yang dirasa pada berminggu-minggu tegangan persiapan acara (wedding jitters). Flashmob mentransformasi resepsi yang tadinya khidmat, formal, kaku bagai simfoni piano menjadi karnaval pesta festival berjiwa muda yang menguras tenaga tapi membahayakan kegembiraan murni yang meluap tak bisa dibendung dari sang punya hajat. Ini melambangkan kebahagiaan sejati nan enerjik untuk disebarluaskan pada hari jadi mereka.', '1. Lampu tiba-tiba disetel kerlap-kerlip atau musik seakan ngadat (prank palsu) sebelum dentum drop bass kencang dihantam dari speaker array.
2. Di saat tamu heran, satu demi satu penari bayangan melompat masuk gelanggang (bisa jadi pengantin sendiri sebagai inisiator dengan melempar jas).
3. Seluruh tamu bersorak ketika formasi tarian barisan depan, belakang mulai selaras mempraktikkan gerakan TikTok / koreografi modern yang jenaka sekaligus lincah memancing tawa pecah tiada henti.', NULL),

('edu-rsp-08', 'resepsi', 'Lempar Bunga Handbouquet', 'Tradisi puncak mitologi resepsi barat yang diadopsi manis dalam semua sirkel milenial. Pengantin berdiri saling merapat membawa buket utama. Di belakang posisi mereka (sejauh kurang lebih 3-5 meter) berjajar serombongan teman/kerabat tamu baik pria maupun wanita dengan status single lajang (belum menikah) yang berteriak-teriak semangat menanti lemparan melekung bagai operan bola dari sang ratu yang dilempar tanpa bisa ia lihat.', '/gambar/edukasi/resepsi-lempar-bunga.webp', 'Kegiatan interaktif bergelimang canda tawa ini diyakini menyalurkan vibrasi magis (aura menular) dari keberuntungan nasib pengantin yang usai menemukan jodohnya pada hari tersebut ke nasib sang calon lajang penangkap bunga. Dalam balutan senda gurau, bunga yang melayang mewakili sepucuk doa kuat agar orang yang paling gesit menggegam bunga itu diberikan rute yang dipermudah dan dilancarkan untuk melangkah segera meminang ke altar pernikahan. Transfer of luck yang menghibur namun syahdu.', '1. Sebelum dilempar, MC menggubah permainan semacam menggiring seluruh muda-mudi berkumpul berdesakan di karpet menanti lemparan.
2. Pengantin memunggungi kumpulan target di area terjauh panggung bawah, mereka bisa berpegangan lalu mengayun buket tersebut berpura-pura melempar di hitungan kesatu (prank kecil dari sang MC).
3. Pada hitungan ketiga final, dengan seluruh sewa tebaran tangan, bunga dicampakkan tinggi ke atas udara membelah ruangan.
4. Tamu lajang berebut dengan gaduh, kadang ada yang melompat, demi menangkap riam melati berbalut pita sutra tersebut diselingi ketawa membahana.', NULL);
